apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dokumentinnhenting
  namespace: aap
  labels:
    team: aap
    sub: dokumentinnhenting
    systemkatalog.nav.no/system: SK-268

spec:
  image: {{image}}
  ingresses:
    - https://aap-dokumentinnhenting.intern.dev.nav.no
  replicas:
    cpuThresholdPercentage: 90
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          - id: ee2a0374-97a6-462e-9a05-3cb7be3d8fc5 #NAIS_TEAM_AAP
  kafka:
    pool: nav-dev
    streams: true
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        diskAutoresize: false
        highAvailability: false
        pointInTimeRecovery: false
        databases:
          - name: dokumentinnhenting
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
      destinations:
        - id: elastic
        - id: loki

  env:
    - name: BEHANDLINGSFLYT_BASE_URL
      value: http://behandlingsflyt
    - name: BEHANDLINGSFLYT_SCOPE
      value: api://dev-gcp.aap.behandlingsflyt/.default
    - name: INTEGRASJON_SYFO_BASE_URL
      value: http://isdialogmelding.teamsykefravr
    - name: INTEGRASJON_SYFO_SCOPE
      value: api://dev-gcp.teamsykefravr.isdialogmelding/.default
    - name: INTEGRASJON_SAF_URL_GRAPHQL
      value: https://saf-q2.dev-fss-pub.nais.io/graphql
    - name: INTEGRASJON_SAF_URL_REST
      value: https://saf-q2.dev-fss-pub.nais.io/rest
    - name: INTEGRASJON_SAF_SCOPE
      value: api://dev-fss.teamdokumenthandtering.saf/.default
    - name: INTEGRASJON_DOKARKIV_URL
      value: https://dokarkiv-q2.dev-fss-pub.nais.io
    - name: INTEGRASJON_DOKARKIV_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv/.default
    - name: INTEGRASJON_BREV_BASE_URL
      value: http://brev
    - name: INTEGRASJON_BREV_SCOPE
      value: api://dev-gcp.aap.brev/.default
    - name: INTEGRASJON_TILGANG_URL
      value: http://tilgang
    - name: INTEGRASJON_TILGANG_SCOPE
      value: api://dev-gcp.aap.tilgang/.default
    - name: INTEGRASJON_API_INTERN_AZP
      value: a809fc0a-eabb-4107-8231-61210adc2b70
    - name: INTEGRASJON_BEHANDLINGSFLYT_AZP
      value: 5b4656d2-e8f0-4df1-9e10-269133df697f
    - name: NAIS_TEAM_AAP
      value: ee2a0374-97a6-462e-9a05-3cb7be3d8fc5
  accessPolicy:
    inbound:
      rules:
        - application: behandlingsflyt
          permissions:
            roles:
              - "syfo-api"
              - "paaminnelse-api"
        - application: paw-patrol
        - application: saksbehandling
        - application: api-intern
        - application: saksbehandling-lokal # For lokal utvikling. IKKE kopier denne til prod-gcp.yaml
        - application: azure-token-generator # For testing i dev. IKKE kopier denne til prod-gcp.yaml
          namespace: nais
          cluster: dev-gcp
          permissions:
            roles:
              - "test-api"
    outbound:
      rules:
        - application: behandlingsflyt
        - application: tilgang
        - application: brev
        - application: isdialogmelding
          namespace: teamsykefravr
      external:
        - host: saf.dev-fss-pub.nais.io
        - host: dokarkiv-q2.dev-fss-pub.nais.io
