[versions]
kelvin = "2.0.181"
behandlingsflyt = "0.0.669"
tilgang = "1.0.242"
aapBrev = "0.0.284"

[libraries]
json = { module = "no.nav.aap.kelvin:json", version.ref = "kelvin" }
infrastructure = { module = "no.nav.aap.kelvin:infrastructure", version.ref = "kelvin" }
dbconnect = { module = "no.nav.aap.kelvin:dbconnect", version.ref = "kelvin" }
dbmigrering = { module = "no.nav.aap.kelvin:dbmigrering", version.ref = "kelvin" }
dbtest = { module = "no.nav.aap.kelvin:dbtest", version.ref = "kelvin" }
motor = { module = "no.nav.aap.kelvin:motor", version.ref = "kelvin" }
motor-api = { module = "no.nav.aap.kelvin:motor-api", version.ref = "kelvin" }
server = { module = "no.nav.aap.kelvin:server", version.ref = "kelvin" }
ktor-openapi-generator = { module = "no.nav.aap.kelvin:ktor-openapi-generator", version.ref = "kelvin" }

# Nav-kontrakter
behandlingsflyt-kontrakt = { module = "no.nav.aap.behandlingsflyt:kontrakt", version.ref = "behandlingsflyt" }
brev-kontrakt = { module = "no.nav.aap.brev:kontrakt", version.ref = "aapBrev" }
tilgang-plugin = { module = "no.nav.aap.tilgang:plugin", version.ref = "tilgang" }

# Test
motor-test-utils = { module = "no.nav.aap.kelvin:motor-test-utils", version.ref = "kelvin" }
