query ($journalpostId: String!) {
    journalpost(
        journalpostId: $journalpostId
    ) {
        journalpostId
        journalposttype
        journalstatus
        tema
        behandlingstema
        relevanteDatoer {
            dato
            datotype
        }
        antallRetur
        kanal
        innsynsregelBeskrivelse
        behandlingstema
        datoOpprettet
        tittel
        dokumenter {
            dokumentInfoId
            tittel
            brevkode
            dokumentstatus
            datoFerdigstilt
            originalJournalpostId
            skjerming
            logiskeVedlegg {
                logiskVedleggId
                tittel
            }
            dokumentvarianter {
                variantformat
                saksbehandlerHarTilgang
                skjerming
            }
        }
    }
}