/*
 * This source file was generated by the Gradle 'init' task
 */
package dokumentinnhenting

import org.junit.jupiter.api.Test
import kotlin.test.assertTrue

class AppTest {
    @Test
    fun appHasAGreeting() {
        assertTrue(true)
    }
}
