CREATE TABLE MOTTATT_DIALOGMELDING
(
    ID                   BIGSERIAL    NOT NULL PRIMARY KEY,
    MSG_ID               UUID         NOT NULL UNIQUE,
    MSG_TYPE             TEXT         NOT NULL,
    MOTTATT_TIDSPUNKT    TIMESTAMP(3) NOT NULL,
    CONVERSATION_REF     UUID         NULL,
    PARENT_REF           UUID         NULL,
    PERSON_IDENT_PASIENT TEXT         NOT NULL,
    LEGE_HPR             TEXT         NULL,
    NAVN_HELSEPERSONELL  TEXT         NOT NULL,
    TEKST_NOTAT_INNHOLD  TEXT         NULL,
    JOURNALPOST_ID       TEXT         NOT NULL,
    SAKSNUMMER           TEXT         NOT NULL,
    OPPRETTET_TID        TIMESTAMP(3) NOT NULL
);

CREATE INDEX IDX_MOTTATT_DIALOGMELDING_MSG_ID ON MOTTATT_DIALOGMELDING (MSG_ID);
CREATE INDEX IDX_MOTTATT_DIALOGMELDING_PERSON_IDENT ON MOTTATT_DIALOGMELDING (PERSON_IDENT_PASIENT);
CREATE INDEX IDX_MOTTATT_DIALOGMELDING_SAKSNUMMER ON MOTTATT_DIALOGMELDING (SAKSNUMMER);
