-- give access to IAM users (GCP)
CREATE EXTENSION IF NOT EXISTS BTREE_GIST;
GRANT ALL ON ALL TABLES IN SCHEMA PUBLIC TO CLOUDSQLIAMUSER;

CREATE TABLE DIALOGMELDING
(
    ID                  BIGSERIAL    NOT NULL PRIMARY KEY,
    DIALOGMELDING_UUID  UUID         NOT NULL UNIQUE,
    BEHANDLER_REF       VARCHAR(40)  NOT NULL,
    PERSON_ID           VARCHAR(50)  NOT NULL,
    SAK_ID              VARCHAR(50)  NOT NULL,
    STATUS              VARCHAR(15)  NULL,
    BESTILLING_UUID     UUID         NULL UNIQUE,
    OPPRETTET_TID       TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_DIALOGMELDING_DIALOGMELDING_UUID ON DIALOGMELDING (DIALOGMELDING_UUID);
CREATE INDEX IDX_DIALOGMELDING_PERSON_ID ON DIALOGMELDING (PERSON_ID);
CREATE INDEX IDX_DIALOGMELDING_SAK_ID ON DIALOGMELDING (SAK_ID);