DROP TABLE DIALOGMELDING;

CREATE TABLE DIALOGMELDING
(
    ID                  BIGSERIAL       NOT NULL PRIMARY KEY,
    DIALOGMELDING_UUID  UUID            NOT NULL UNIQUE,
    BEHANDLER_REF       VARCHAR(40)     NOT NULL,
    BEHANDLER_NAVN      VARCHAR(60)     NOT NULL,
    VEILEDER_NAVN       VARCHAR(60)     NOT NULL,
    PERSON_ID           VARCHAR(50)     NOT NULL,
    DOKUMENTASJONTYPE   VARCHAR(30)     NOT NULL,
    FRITEKST            TEXT            DEFAULT '' NOT NULL,
    SAKSNUMMER          VARCHAR(25)     NOT NULL,
    STATUS              VARCHAR(15)     NULL,
    FLYTSTATUS          VARCHAR(15)     NULL,
    OPPRETTET_TID       TIMESTAMP(3)    DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_DIALOGMELDING_DIALOGMELDING_UUID ON DIALOGMELDING (DIALOGMELDING_UUID);
CREATE INDEX IDX_DIALOGMELDING_PERSON_ID ON DIALOGMELDING (PERSON_ID);
CREATE INDEX IDX_DIALOGMELDING_SAKSNUMMER ON DIALOGMELDING (SAKSNUMMER);

CREATE TABLE JOBB
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    STATUS        VARCHAR(50)  DEFAULT 'KLAR'            NOT NULL,
    TYPE          VARCHAR(50)                            NOT NULL,
    SAK_ID        BIGINT                                 NULL,
    BEHANDLING_ID BIGINT NULL,
    PARAMETERS    TEXT NULL,
    PAYLOAD       TEXT NULL,
    NESTE_KJORING TIMESTAMP(3)                           NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_JOBB_STATUS ON JOBB (STATUS, SAK_ID, BEHANDLING_ID, NESTE_KJORING);
-- Legger inn en unik index per type for en sak+behandling for åpne oppgaver
CREATE UNIQUE INDEX UIDX_JOBB_STATUS_SAK_BEHANDLING_TYPE ON JOBB (TYPE, SAK_ID, BEHANDLING_ID) WHERE (
    STATUS IN ('KLAR', 'FEILET') AND SAK_ID IS NOT NULL AND BEHANDLING_ID IS NOT NULL);

CREATE TABLE JOBB_HISTORIKK
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    JOBB_ID       BIGINT                                 NOT NULL REFERENCES JOBB (ID),
    STATUS        VARCHAR(50)                            NOT NULL,
    FEILMELDING   TEXT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_JOBB_HISTORIKK_STATUS ON JOBB_HISTORIKK (JOBB_ID, STATUS);