CREATE INDEX IDX_DIALOGMELDING_SAMTALE_REF_PERSON_ID
    ON DIALOGMELDING (SAMTALE_REF, PERSON_ID);

CREATE INDEX IDX_MOTTATT_DIALOGMELDING_CONVERSATION_REF_PERSON_IDENT
    ON MOTTATT_DIALOGMELDING (CONVERSATION_REF, PERSON_IDENT_PASIENT);
