DROP TABLE DIALOGMELDING;

CREATE TABLE DIALOGMELDING
(
    ID                              BIGSERIAL       NOT NULL PRIMARY KEY,
    DIALOGMELDING_UUID              UUID            NOT NULL UNIQUE,
    BEHANDLER_REF                   VARCHAR(40)     NOT NULL,
    BEHANDLER_NAVN                  VARCHAR(60)     NOT NULL,
    VEILEDER_NAVN                   VARCHAR(60)     NOT NULL,
    PERSON_ID                       VARCHAR(50)     NOT NULL,
    DOKUMENTASJONTYPE               VARCHAR(30)     NOT NULL,
    FRITEKST                        TEXT            DEFAULT '' NOT NULL,
    SAKSNUMMER                      VARCHAR(25)     NOT NULL,
    STATUS                          VARCHAR(15)     NULL,
    FLYTSTATUS                      VARCHAR(15)     NULL,
    PERSON_NAVN                     VARCHAR(60)     NOT NULL DEFAULT 'UKJENT',
    STATUS_TEKST                    VARCHAR(60)     NULL,
    BEHANDLINGSREFERANSE            UUID            NOT NULL,
    OPPRETTET_TID                   TIMESTAMP(3)    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TIDLIGERE_BESTILLING_REFERANSE  VARCHAR(60)     NULL,
    JOURNALPOST_ID                  VARCHAR(60)     NULL,
    DOKUMENT_ID                     VARCHAR(60)     NULL,
    BEHANDLER_HPR_NR                VARCHAR(60)     NOT NULL
);
CREATE INDEX IDX_DIALOGMELDING_DIALOGMELDING_UUID ON DIALOGMELDING (DIALOGMELDING_UUID);
CREATE INDEX IDX_DIALOGMELDING_PERSON_ID ON DIALOGMELDING (PERSON_ID);
CREATE INDEX IDX_DIALOGMELDING_SAKSNUMMER ON DIALOGMELDING (SAKSNUMMER);